name: Deploy (Vercel, personal)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & Build
        run: |
          if [ -f package-lock.json ]; then npm ci || npm install; else npm install; fi
          npm run -s build

      - name: Vercel pull (prod)
        run: npx -y vercel@latest pull --yes --environment=production --token "$VERCEL_TOKEN"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: whoami (fail fast)
        run: npx -y vercel@latest whoami --token "$VERCEL_TOKEN"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy prebuilt (prod) with retries
        run: |
          set -e
          for i in 1 2 3; do
            echo "Attempt #$i"
            npx -y vercel@latest deploy --prebuilt --prod --yes --token "$VERCEL_TOKEN" && break || sleep 10
          done
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
