name: E2E Testing with Playwright

on:
  push:
    branches: [ main, develop, 'feat/**' ]
  pull_request:
    branches: [ main, develop ]

concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
      fail-fast: false
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: 'npm'
        
    - run: npm ci
    - run: npx playwright install --with-deps
    - run: npm run build:e2e
    
    - name: Run Playwright tests
      env:
        PORT: 3100
        BASE_URL: http://localhost:3100
        NEXT_PUBLIC_SITE_URL: http://localhost:3100
        DISABLE_CANONICAL_REDIRECTS: "1"
        CI: "1"
      run: npm run test:e2e:ci -- --project=${{ matrix.browser }}
      
    - name: Upload Playwright report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-${{ matrix.browser }}
        path: playwright-report
        retention-days: 3
        
    - name: Upload traces
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: traces-${{ matrix.browser }}
        path: test-results/**/*.zip
        retention-days: 3