name: E2E Testing with Playwright

on:
  push:
    branches: [ main, develop, 'feat/**' ]
  pull_request:
    branches: [ main, develop ]

concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
      fail-fast: false
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        node-version: '20.x'
        cache: 'npm'
        
    - run: npm ci
    - run: npx playwright install --with-deps
    - run: NEXT_TELEMETRY_DISABLED=1 npm run -s build
    - run: (npm run -s start &) && npx wait-on http://127.0.0.1:3000
    - env:
        PLAYWRIGHT_BASE_URL: http://127.0.0.1:3000
        E2E: '1'
        NEXT_TELEMETRY_DISABLED: '1'
      run: npx playwright test --project=${{ matrix.browser }} --reporter=line
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ matrix.browser }}
        path: playwright-report
        retention-days: 3