name: LHCI
on: [workflow_dispatch]
jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - name: Run Lighthouse CI on production
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            https://marlowgate.com/
            https://marlowgate.com/best/forex-brokers-jp
          configPath: ./.lighthouse/lhci.json
          uploadArtifacts: true