name: Manual Vercel Deploy

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'components/**'
      - 'public/**'
      - 'content/**'
      - 'scripts/**'
      - 'next.config.*'
      - 'vercel.json'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/manual-vercel-deploy.yml'

concurrency:
  group: vercel-prod
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build (local)
        run: pnpm build

      # == Persistent verification (safe logs) ==
      - name: Verify Vercel credentials (whoami + fingerprints)
        run: |
          echo "## Vercel whoami"
          npx vercel whoami --token=${{ secrets.VERCEL_TOKEN }}

          echo "## Fingerprints (SHA256)"
          echo -n "${{ secrets.VERCEL_TOKEN }}"   | sha256sum | awk '{print $1}' > token.sha
          echo -n "${{ secrets.VERCEL_ORG_ID }}"  | sha256sum | awk '{print $1}' > org.sha
          echo -n "${{ secrets.VERCEL_PROJECT_ID }}" | sha256sum | awk '{print $1}' > project.sha

          echo "::notice title=VERCEL_TOKEN_SHA256::$(cat token.sha)"
          echo "::notice title=VERCEL_ORG_ID_SHA256::$(cat org.sha)"
          echo "::notice title=VERCEL_PROJECT_ID_SHA256::$(cat project.sha)"

      - name: Vercel pull (prod)
        run: npx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel (prebuilt, prod, single)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: npx vercel deploy --prebuilt --prod --yes
