name: Manual Vercel Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deploy target (production or preview)"
        required: true
        default: "production"
        type: choice
        options: [production, preview]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Pull Vercel Environment
        run: vercel pull --yes --environment=${{ inputs.environment }} --token=$VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Build
        run: |
          if [ "${{ inputs.environment }}" = "production" ]; then
            vercel build --prod --token=$VERCEL_TOKEN
          else
            vercel build --token=$VERCEL_TOKEN
          fi
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Deploy (prebuilt)
        run: |
          if [ "${{ inputs.environment }}" = "production" ]; then
            vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
          else
            vercel deploy --prebuilt --token=$VERCEL_TOKEN
          fi
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
