name: Reviews Ingest (docx/pdf -> md)

on:
  workflow_dispatch:
  push:
    paths:
      - 'content_source/reviews/**'

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pandoc
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pandoc

      - name: Ensure output dir
        run: mkdir -p content/reviews

      - name: Convert DOCX/PDF to Markdown (GFM)
        run: |
          shopt -s nullglob
          exit_code=0
          for f in content_source/reviews/*; do
            base=$(basename "$f")
            name="${base%.*}"
            ext="${base##*.}"
            if [[ "$ext" == "docx" || "$ext" == "pdf" ]]; then
              pandoc "$f" -f docx -t gfm --wrap=none -o "content/reviews/${name}.md" || exit_code=1
            elif [[ "$ext" == "md" ]]; then
              cp "$f" "content/reviews/${name}.md"
            fi
          done
          exit $exit_code

      - name: Normalize headings (H2/H3)
        run: |
          for m in content/reviews/*.md; do
            # 見出し1を見出し2に揃える（万一H1が混ざった時の保険）
            sed -i 's/^#\s\+/## /g' "$m"
          done

      - name: Commit converted files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(reviews): convert to markdown via pandoc"
          file_pattern: content/reviews/*.md
